spring:
  application:
    name: spring-cloud-server
server:
  port: 8080

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


#zuul:
#  # service will be mapped under /api uri
#  prefix: /api
#  routes:
#    stock-db-service:
#      path: /stock-db-service/**
#      url: http://localhost:8083
#    stock-service:
#      path: /stock-service/**
#      url: http://localhost:8082